### PR TITLE
Code update

### PR DESCRIPTION
**Pull request by TFLTV**

### CODE REVIEW

**Comment by chicken-nugget1104** [comment]
Look's good
Gonna do like 1 manual change then it will be good to merge.

**Comment by TFLTV** [comment]
destroy on hit is on by default

**Comment by chicken-nugget1104** [comment]
> destroy on hit is on by default

Dang
Didn't know that...

**Comment by TFLTV** [comment]
should the moving arena in zigzagmovingarenaedtion be dealt in the og? so we dont have change both
```
if Utils.pick({false,true}) then self.moving_arena = true end
```

**Comment by TFLTV** [comment]
Oh this is already merged

**Comment by chicken-nugget1104** [comment]
> should the moving arena in zigzagmovingarenaedtion be dealt in the og? so we dont have change both
> 
> ```
> if Utils.pick({false,true}) then self.moving_arena = true end
> ```

you diod that so

**Pull request merged**
